image: node:16.13.2-alpine

stages:
  - test
  - analyze

cache:
  paths:
    - node_modules/
    - .yarn

coverage:
  stage: test
  script:
    - npm i -g lerna
    - lerna bootstrap
    - lerna run build
    - yarn coverage
  allow_failure: true
  only:
    - main
  tags:
    - gits-docker
  artifacts:
    paths:
      - $CI_PROJECT_DIR/coverage/

analyze:sonar:
  stage: analyze
  variables:
    SONAR_USER_HOME: '${CI_PROJECT_DIR}/.sonar'
    GIT_DEPTH: 0
  image:
    name: sonarsource/sonar-scanner-cli:4.7
    entrypoint: ['']
  cache:
    key: '${CI_JOB_NAME}'
    paths:
      - .sonar/cache
  script:
    - sonar-scanner -Dsonar.projectKey=$CI_PROJECT_NAME -Dsonar.sources=packages -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_USER -Dsonar.password=$SONAR_PASSWORD
  allow_failure: true
  only:
    - main
  tags:
    - gits-docker
